http:
  routers:
    sonarr:
      entryPoints:
      - web
      service: sonarr
      rule: PathPrefix(`/tv`)
      priority: 42
      
  services:
    sonarr:
      loadBalancer:
        servers:
        - url: http://sonarr:8989
